service: kmullaney-sls

useDotenv: true

provider:
  name: aws
  region: us-west-2
  stage: dt-headers
  timeout: 4
  logRetentionInDays: 3
  tags:
    owner: kmullaney
    reason: demo
    description: "dt headers"
  stackTags:
    owner: kmullaney
    reason: demo
    description: "dt headers"
  environment:
    NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    NEW_RELIC_EXTENSION_LOG_LEVEL: DEBUG
    NEW_RELIC_NATIVE_METRICS_ENABLED: false                      # Reduce cold start duration by not collecting VM metrics

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}    # New Relic account ID
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY} # User api key
    disableAutoSubscription: true             # Don't create a subscription filter to the newrelic-log-ingestion function
    enableFunctionLogs: true                  # Send logs via [NR_EXT]
    logEnabled: true                          # Agent logs
    logLevel: info                            # Agent log level
    debug: true                               # Serverless Framework debug

# package:
#   individually: true

functions:
  nodejs18x:
    description: accept or insert dt headers
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.lambda_handler
    runtime: nodejs18.x
    package:
      patterns:
        - '!node_modules/**'
        - 'node_modules/axios/**'
        - 'function.js'
    provisionedConcurrency: 0
