service: kmullaney-sls-dt-headers

provider:
  name: aws
  runtime: java11
  region: us-west-1
  stage: dev

package:
  artifact: 'target/${self:service}-${self:provider.stage}.jar'

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    logLevel: debug
functions:
  listProducts:
    handler: com.serverless.Handler


