service: kmullaney-dt-headers

useDotenv: true

provider:
  name: aws
  region: ${env:AWS_DEFAULT_REGION}
  stage: "dev"
  timeout: 4
  logRetentionInDays: 14
  tags:
    owner: kmullaney
    reason: case
    description: "123456"
  stackTags:
    owner: kmullaney
    reason: case
    description: "123456"
  environment:
    NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    NEW_RELIC_EXTENSION_LOG_LEVEL: ${env:NEW_RELIC_EXTENSION_LOG_LEVEL}

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}    # New Relic account ID
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY} # User api key
    disableAutoSubscription: true             # Don't create a subscription filter to the newrelic-log-ingestion function
    enableFunctionLogs: true                  # Send logs via [NR_EXT]
    logEnabled: true                          # Node agent logs
    logLevel: info                            # Node agent log level
    debug: true                               # Serverless Framework debug

# package:
#   individually: true

functions:
  nodejs14x:
    description: accept or insert dt headers
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.lambda_handler
    runtime: nodejs14.x
    package:
      patterns:
        - '!node_modules/**'
        - 'node_modules/axios/**'
        - 'function.js'
    provisionedConcurrency: 0
