version: '3'

services:
  collector-load-test:
    build:
      context: ../${RUNTIME}/
      dockerfile: Dockerfile
    image: collector-load-test:0.1.0
    networks:
      - otel
    environment:
      OTEL_SERVICE_NAME: 'collector-load-test'
      OTEL_LOGS_EXPORTER: 'debug'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector'
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: 'delta'
      OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT: 4095
      METRICS_PER_SECOND: ${METRICS_PER_SECOND}
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.95.0
    networks:
      - otel
    volumes:
      - ./${COLLECTOR_CONFIG}:/collector.yaml
    command: ["--config=/collector.yaml"]
    environment:
      NEW_RELIC_LICENSE_KEY: '${NEW_RELIC_LICENSE_KEY}'
    ports:
      - 1777:1777 # pprof extension | https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/pprofextension/README.md
      # - 8888:8888 # Prometheus metrics exposed by the collector
      # - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension | https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
      - 4317:4317 # OTLP gRPC receiver
      # - 4318:4318 # OTLP http receiver
      - 25679:25679 # zpages extension | https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/zpagesextension/README.md

networks:
  otel:
