service: kmullaney

useDotenv: true

provider:
  name: aws
  region: ${env:AWS_DEFAULT_REGION}
  stage: dev
  runtime: nodejs18.x
  timeout: 4
  logRetentionInDays: 14
  tags:
    owner: kmullaney
    reason: testing aws
    description: see if any issues with CF deployment
  stackTags:
    owner: kmullaney
    reason: testing aws
    description: see if any issues with CF deployment
  environment:
    # NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    NEW_RELIC_EXTENSION_LOG_LEVEL: ${env:NEW_RELIC_EXTENSION_LOG_LEVEL}

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    # disableLicenseKeySecret: true
    logEnabled: true
    logLevel: info
    debug: true

package:
  individually: true

functions:
  nodejs18x:
    description: a test nodejs18x function
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.lambda_handler
    package:
      exclude:
        - ./**
      include:
        - ./function.mjs
        # - ./node_modules/aws-sdk/*
    provisionedConcurrency: 0
