FROM amazonlinux:2023

RUN yum -y update && \
    yum -y install golang

WORKDIR /build

COPY src/* ./

RUN go mod download

RUN env GOARCH=amd64 GOOS=linux go build -tags lambda.norpc -ldflags="-s -w" -o bootstrap
