# Define the New Relic pre-built image
FROM public.ecr.aws/newrelic-lambda-layers-for-docker/newrelic-lambda-layers-nodejs:22 AS layer

# Define the base image
FROM public.ecr.aws/lambda/nodejs:22

# Layer code
COPY --from=layer /opt/ /opt/

# Copy the function code and package.json
COPY function.js package.json ./

# Install any additional dependencies
RUN npm install

# Set the CMD override to use New Relic's handler wrapper
CMD [ "newrelic-lambda-wrapper.handler" ]
