service: kmullaney

useDotenv: true

provider:
  name: aws
  region: ${env:AWS_DEFAULT_REGION}
  stage: "00059605"
  timeout: 30
  logRetentionInDays: 14
  tags:
    owner: kmullaney
    reason: ticket
    description: "00059605"
  stackTags:
    owner: kmullaney
    reason: ticket
    description: "00059605"
  environment:
    NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    NEW_RELIC_EXTENSION_LOG_LEVEL: ${env:NEW_RELIC_EXTENSION_LOG_LEVEL}
    NEW_RELIC_LOG_LEVEL: info
    NEW_RELIC_LOG: stderr
    NEW_RELIC_PACKAGE_REPORTING_ENABLED: false   # disable package reporting feature to improve cold start times

plugins:
  - serverless-python-requirements
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    disableLicenseKeySecret: false
    debug: true
  pythonRequirements:
    fileName: ./requirements.txt

package:
  individually: true

functions:
  python39:
    description: Test with cURL to endpoint.
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.lambda_handler
    package:
      exclude:
        - ./**
      include:
        - ./function.py
    # cURL is removed from Lambda runtimes > python3.7
    runtime: python3.9
    provisionedConcurrency: 0
