service: kmullaney-sls

useDotenv: true

provider:
  name: aws
  region: us-west-2
  stage: load-test
  runtime: nodejs18.x
  logRetentionInDays: 7
  tags:
    owner: kmullaney
    reason: case 00156124
    description: load testing newrelic-log-ingestion function
  stackTags:
    owner: kmullaney
    reason: case 00156124
    description: load testing newrelic-log-ingestion function

package:
  individually: true

functions:
  nodejs18x:
    description: a test nodejs18x function
    # events:
    #   - schedule: rate(1 minute)
    handler: function.handler
    memorySize: 256
    timeout: 3
    package:
      patterns:
        - "function.mjs"
    # provisionedConcurrency: 2
    # reservedConcurrency: 1

  invoker:
    description: a nodejs18x function to invoke our pumpkin function
    events:
      - schedule: rate(5 minutes)
    handler: invoker.handler
    memorySize: 128
    timeout: 65
    package:
      patterns:
        - "node_modules/**"
        - "invoker.js"
    # provisionedConcurrency: 0
    # reservedConcurrency: 1
