service: kmullaney-sls-new-ips

useDotenv: true

provider:
  name: aws
  region: us-west-2
  stage: dev
  timeout: 10
  logRetentionInDays: 3
  tags:
    owner: kmullaney
    reason: case
    description: "00144272"
  stackTags:
    owner: kmullaney
    reason: case
    description: "00144272"
  environment:
    NEW_RELIC_USER_KEY: ${env:NEW_RELIC_USER_KEY}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    fileName: ./requirements.txt

package:
  patterns:
    - '!./**'
    - 'function.py'

# package:
#   individually: true

functions:
  python39:
    description: test new ip ranges
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.lambda_handler
    runtime: python3.9
    provisionedConcurrency: 0
