service: kmullaney-sls

useDotenv: true

provider:
  name: aws
  region: us-west-2
  stage: curl
  timeout: 10
  logRetentionInDays: 1
  tags:
    owner: kmullaney
    reason: case
    description: "123456"
  stackTags:
    owner: kmullaney
    reason: case
    description: "123456"
  environment:
    NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    # NEW_RELIC_LICENSE_KEY: ${env:NEW_RELIC_LICENSE_KEY}
    NEW_RELIC_EXTENSION_LOG_LEVEL: DEBUG
    NEW_RELIC_NATIVE_METRICS_ENABLED: false                      # Reduce cold start duration by not collecting VM metrics
    # NEW_RELIC_LOG_LEVEL: info
    # NEW_RELIC_LOG: stderr
    NEW_RELIC_PACKAGE_REPORTING_ENABLED: false   # disable package reporting feature to improve cold start times

plugins:
  - serverless-python-requirements
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_USER_API_KEY}
    # disableLicenseKeySecret: false
    logEnabled: true
    logLevel: debug
    debug: true
    # layerArn: arn:aws:lambda:us-west-2:451483290750:layer:NewRelicPython37:97
  pythonRequirements:
    fileName: ./requirements.txt

package:
  individually: true

functions:
  python37:
    description: print dt headers
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.lambda_handler
    package:
      exclude:
        - ./**
      include:
        - ./function.py
    # cURL is removed from Lambda runtimes > python3.7
    runtime: python3.7
    provisionedConcurrency: 0
