service: kmullaney-ext-only

useDotenv: true

provider:
  name: aws
  region: ${env:AWS_DEFAULT_REGION}
  stage: "dev"
  timeout: 4
  logRetentionInDays: 3
  tags:
    owner: kmullaney
    reason: demo
    description: "demo a Lambda using SLS deploy"
  stackTags:
    owner: kmullaney
    reason: demo
    description: "demo a Lambda using SLS deploy"
  environment:
    # NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    NEW_RELIC_EXTENSION_LOG_LEVEL: ${env:NEW_RELIC_EXTENSION_LOG_LEVEL}
    NEW_RELIC_APP_NAME: kmullaney-extension-only-layer-serverless-nodejs16x
    NEW_RELIC_NO_CONFIG_FILE: true
    NEW_RELIC_SERVERLESS_MODE_ENABLED: true

plugins:
  - serverless-offline
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}            # New Relic account ID
    trustedAccountKey: ${env:NEW_RELIC_ACCOUNT_ID}    # New Relic account ID or parent ID
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}         # User api key
    disableAutoSubscription: true                     # Don't create a subscription filter to the newrelic-log-ingestion function
    disableLicenseKeySecret: true                     # Use NEW_RELIC_LICENSE_KEY env var instead of AWS Secrets Manager secret
    enableFunctionLogs: true                          # Send logs via [NR_EXT]
    enableIntegration: false                          # Don't create an api polling integration (already have Metric Streams)
    logEnabled: true                                  # Node agent logs
    logLevel: debug                                   # Node agent log level
    debug: true                                       # Serverless Framework debug
    manualWrapping: true                              # use legacy wrapper (agent not in layer)
    layerArn: arn:aws:lambda:us-west-2:451483290750:layer:NewRelicLambdaExtension:34

package:
  individually: true

functions:
  nodejs16x:
    description: accept or insert dt headers
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.lambda_handler
    runtime: nodejs16.x
    package:
      patterns:
        - 'node_modules/**'
        - 'function.js'
    provisionedConcurrency: 0
