service: kmullaney-sls-java

useDotenv: true

provider:
  name: aws
  region: us-west-2
  stage: dev
  timeout: 10
  logRetentionInDays: 3
  tags:
    owner: kmullaney
    reason: test
    description: test Java17 instrumentation for NR_LAMBDA_MONITORING payload
  stackTags:
    owner: kmullaney
    reason: test
    description: test Java17 instrumentation for NR_LAMBDA_MONITORING payload

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}            # New Relic account ID
    trustedAccountKey: ${env:NEW_RELIC_ACCOUNT_ID}    # New Relic account ID or parent ID
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}         # User api key
    disableAutoSubscription: false                    # Enable/disable creation of a subscription filter to the newrelic-log-ingestion function
    disableLicenseKeySecret: false                    # Enable/disable AWS Secrets Manager secret
    enableExtension: false                            # Enable/disable Extension for sending telemetry directly to New Relic
    enableFunctionLogs: true                          # Send logs
    enableIntegration: false                          # Don't create an api polling integration (already have Metric Streams)
    logEnabled: true                                  # Agent logs
    logLevel: debug                                   # Agent log level
    debug: true                                       # Serverless Framework debug
    # layerArn: arn:aws:lambda:us-west-2:451483290750:layer:NewRelicJava17:2   # uncomment if you want to pin a layer version

package:
  artifact: 'target/${self:service}-${self:provider.stage}-1.0.jar'

functions:
  java17:
    description: test Java17 instrumentation
    handler: com.newrelic.lambda.example.App::handleRequest
    runtime: java17
    provisionedConcurrency: 0
