service: kmullaney-load-test

useDotenv: true

provider:
  name: aws
  region: ${env:AWS_DEFAULT_REGION}
  stage: dev
  runtime: nodejs18.x
  memorySize: 128
  logRetentionInDays: 3
  tags:
    owner: kmullaney
    reason: case 00156124
    description: load testing newrelic-log-ingestion function
  stackTags:
    owner: kmullaney
    reason: case 00156124
    description: load testing newrelic-log-ingestion function

package:
  individually: true

functions:
  nodejs18x:
    description: a test nodejs18x function
    # events:
    #   - schedule: rate(1 minute)
    handler: function.lambda_handler
    timeout: 4
    package:
      patterns:
        - 'node_modules/**'
        - 'function.mjs'
    provisionedConcurrency: 10
    # reservedConcurrency: 1

  invoker:
    description: a nodejs18x function to invoke our pumpkin function
    events:
      - schedule: rate(1 minute)
    handler: invoker.handler
    timeout: 65
    package:
      patterns:
        - 'node_modules/**'
        - 'invoker.js'
    provisionedConcurrency: 0
    # reservedConcurrency: 1
