service: kmullaney-sls

useDotenv: true

provider:
  name: aws
  region: us-west-2
  stage: cw
  timeout: 4
  logRetentionInDays: 3
  tags:
    owner: kmullaney
    reason: example
    description: send logs and payloads through CloudWatch
  stackTags:
    owner: kmullaney
    reason: example
    description: send logs and payloads through CloudWatch
  environment:
    NEW_RELIC_NATIVE_METRICS_ENABLED: false           # Reduce cold start duration by not collecting VM metrics

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}            # New Relic account ID
    apiKey: ${env:NEW_RELIC_USER_API_KEY}             # User api key
    enableExtension: false                            # enable/disable extension
    cloudWatchFilter: '*'                             # send all logs to newrelic-log-ingestion function

package:
  individually: true

functions:
  nodejs20x:
    description: demo log ingestion
    handler: function.handler
    runtime: nodejs20.x
    package:
      patterns:
        - 'function.js'
    environment:
      NEW_RELIC_APP_NAME: kmullaney-sls-cw-nodejs20x
