service: kmullaney

useDotenv: true

provider:
  name: aws
  region: ${env:AWS_DEFAULT_REGION}
  stage: "dt-headers"
  timeout: 10
  logRetentionInDays: 14
  tags:
    owner: kmullaney
    reason: case
    description: "00084843"
  stackTags:
    owner: kmullaney
    reason: case
    description: "00084843"
  environment:
    NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    # NEW_RELIC_LICENSE_KEY: ${env:NEW_RELIC_LICENSE_KEY}
    NEW_RELIC_EXTENSION_LOG_LEVEL: ${env:NEW_RELIC_EXTENSION_LOG_LEVEL}
    # NEW_RELIC_LOG_LEVEL: info
    # NEW_RELIC_LOG: stderr

plugins:
  - serverless-python-requirements
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    # disableLicenseKeySecret: false
    logEnabled: true
    logLevel: debug
    debug: true
    # layerArn: arn:aws:lambda:us-west-2:451483290750:layer:NewRelicPython37:97
  pythonRequirements:
    fileName: ./requirements.txt

package:
  individually: true

functions:
  python39:
    description: Test dt headers
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.lambda_handler
    package:
      exclude:
        - ./**
      include:
        - ./function.py
    # cURL is removed from Lambda runtimes > python3.7
    runtime: python3.9
    provisionedConcurrency: 0
