service: kmullaney

useDotenv: true

provider:
  name: aws
  region: us-west-2
  stage: dev
  timeout: 30
  logRetentionInDays: 3
  tags:
    owner: kmullaney
    reason: testing
    description: test NEW_RELIC_LABELS
  stackTags:
    owner: kmullaney
    reason: testing
    description: test NEW_RELIC_LABELS
  environment:
    # NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    NEW_RELIC_EXTENSION_LOG_LEVEL: ${env:NEW_RELIC_EXTENSION_LOG_LEVEL}
    NEW_RELIC_APP_NAME: kmullaney-dev-labels
    NEW_RELIC_LABELS: customLabel:customValue;customLabel2:customValue2

plugins:
  - serverless-python-requirements
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}            # New Relic account ID
    trustedAccountKey: ${env:NEW_RELIC_ACCOUNT_ID}    # New Relic account ID or parent ID
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}         # User api key
    disableAutoSubscription: true                     # Don't create a subscription filter to the newrelic-log-ingestion function
    disableLicenseKeySecret: false                    # Use NEW_RELIC_LICENSE_KEY env var or AWS Secrets Manager secret
    enableFunctionLogs: true                          # Send logs via [NR_EXT]
    enableIntegration: false                          # Don't create an api polling integration (already have Metric Streams)
    logEnabled: true                                  # Node agent logs
    logLevel: debug                                   # Node agent log level
    debug: true                                       # Serverless Framework debug
    # layerArn: arn:aws:lambda:us-west-2:451483290750:layer:NewRelicNodeJS18X:48   # uncomment if you want to pin a layer version
  pythonRequirements:
    fileName: ./requirements.txt

package:
  individually: true

functions:
  labels:
    description: Test NEW_RELIC_LABELS
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.handler
    runtime: python3.10
    package:
      patterns:
        - 'node_modules/**'
        - 'function.py'
    provisionedConcurrency: 0
