service: kmullaney

useDotenv: true

provider:
  name: aws
  region: ${env:AWS_DEFAULT_REGION}
  stage: "dt-headers-2"
  timeout: 10
  logRetentionInDays: 14
  tags:
    owner: kmullaney
    reason: case
    description: "123456"
  stackTags:
    owner: kmullaney
    reason: case
    description: "123456"
  environment:
    NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    NEW_RELIC_EXTENSION_LOG_LEVEL: ${env:NEW_RELIC_EXTENSION_LOG_LEVEL}

plugins:
  - serverless-python-requirements
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}    # New Relic account ID
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY} # User api key
    disableAutoSubscription: true             # Don't create a subscription filter to the newrelic-log-ingestion function
    enableFunctionLogs: true                  # Send logs via [NR_EXT]
    logEnabled: true                          # Python agent logs
    logLevel: info                            # Python agent log level
    debug: true                               # Serverless Framework debug
  pythonRequirements:
    fileName: ./requirements.txt

package:
  individually: true

functions:
  python37:
    description: print dt headers
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.lambda_handler
    package:
      exclude:
        - ./**
      include:
        - ./function.py
    # cURL is removed from Lambda runtimes > python3.7
    runtime: python3.7
    provisionedConcurrency: 0
