service: kmullaney

useDotenv: true

provider:
  name: aws
  region: ${env:AWS_DEFAULT_REGION}
  stage: "00102778"
  runtime: nodejs16.x
  timeout: 30
  logRetentionInDays: 14
  tags:
    owner: kmullaney
    reason: ticket
    description: "00102778"
  stackTags:
    owner: kmullaney
    reason: ticket
    description: "00102778"
  environment:
    # NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    NEW_RELIC_EXTENSION_LOG_LEVEL: ${env:NEW_RELIC_EXTENSION_LOG_LEVEL}

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    disableLicenseKeySecret: true
    logEnabled: true
    logLevel: info
    debug: true

package:
  individually: true

functions:
  nodejs16x:
    description: a test nodejs16x function
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.lambda_handler
    package:
      exclude:
        - ./**
      include:
        - ./function.js
    provisionedConcurrency: 0
