service: kmullaney-sls

useDotenv: true

provider:
  name: aws
  region: us-west-2
  stage: "00082952"
  timeout: 4
  logRetentionInDays: 3
  tags:
    owner: kmullaney
    reason: ticket
    description: "00082952"
  stackTags:
    owner: kmullaney
    reason: ticket
    description: "00082952"
  environment:
    # NEW_RELIC_LICENSE_KEY_SECRET: ${env:NEW_RELIC_LICENSE_KEY_SECRET}
    NEW_RELIC_EXTENSION_LOG_LEVEL: DEBUG
    NEW_RELIC_NATIVE_METRICS_ENABLED: false                      # Reduce cold start duration by not collecting VM metrics

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: ${env:NEW_RELIC_ACCOUNT_ID}
    apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
    # disableLicenseKeySecret: true
    logEnabled: true
    logLevel: info
    debug: true

package:
  individually: true

functions:
  nodejs16x:
    description: print environment
    # events:
    #   - schedule: rate(5 minutes)
    handler: function.lambda_handler
    runtime: nodejs16.x
    package:
      exclude:
        - ./**
      include:
        - ./function.js
    provisionedConcurrency: 0

  # nodejs18x:
  #   description: print environment
  #   # events:
  #   #   - schedule: rate(5 minutes)
  #   handler: function.lambda_handler
  #   runtime: nodejs18.x
  #   package:
  #     exclude:
  #       - ./**
  #     include:
  #       - ./function.js
  #   provisionedConcurrency: 0
