AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: And example of a simple instrumented NodeJS Lambda

Parameters:
  NRAccountId:
    Type: String
    Description: Your New Relic account ID; necessary for distributed tracing.
    AllowedPattern: '[0-9]+'

  NRTrustedAccountKey:
    Type: String
    Description: Your New Relic parent account ID or account ID if no parent; necessary for distributed tracing.
    AllowedPattern: '[0-9]+'

Resources:
  KmullaneyNodejs18ESM:
    Type: AWS::Serverless::Function
    Properties:
      # In this example, we're using the SAM CLI to package and deploy our lambda. SAM will transform this value during the publish step.
      CodeUri: src/
      Description: A simple Lambda, with New Relic telemetry
      FunctionName: kmullaney-nodejs18-esm
      # If not using ESM, this should be newrelic-lambda-wrapper.handler provided by the instrumentation layer.
      # If using ESM, bypass newrelic-lambda-wrapper.handler to avoid RITM slow dependency loading by setting the actual function handler here.
      Handler: function.handler
      Runtime: nodejs18.x
      MemorySize: 256
      Timeout: 20
      # Currently, we don't support Image based PackageType
      PackageType: Zip
      Environment:
        Variables:
          NEW_RELIC_NO_CONFIG_FILE: true                               # Node agent uses environment variables in Lambda
          NEW_RELIC_APP_NAME: kmullaney-nodejs18-esm                   # Should be set but not used in the New Relic UI, entity names come from the AWS integration
          NEW_RELIC_ACCOUNT_ID: !Sub ${NRAccountId}                    # New Relic account ID
          NEW_RELIC_TRUSTED_ACCOUNT_KEY: !Sub ${NRTrustedAccountKey}   # New Relic account ID or parent ID
          NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: true                 # Send logs via [NR_EXT]
          NEW_RELIC_EXTENSION_LOG_LEVEL: DEBUG                         # Extension log level
          NEW_RELIC_LOG_ENABLED: true                                  # Node agent logs
          NEW_RELIC_LOG: stdout                                        # Node agent log path
          NEW_RELIC_LOG_LEVEL: trace                                   # Node agent log level
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicNodeJS18X:51
      Policies:
        # This policy allows the lambda to know the value of the New Relic license key. We need this so
        # that we can send telemetry back to New Relic
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !ImportValue NewRelicLicenseKeySecret-NewRelic-LicenseKeySecretARN

  KmullaneyNodejs18LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${KmullaneyNodejs18ESM}'
      RetentionInDays: 3
