AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: And example of a simple instrumented NodeJS Lambda

Parameters:
  NRAccountId:
    Type: String
    Description: Your New Relic account ID; necessary for distributed tracing.
    AllowedPattern: "[0-9]+"
  NRTrustedAccountKey:
    Type: String
    Description: Your New Relic parent account ID or account ID if no parent; necessary for distributed tracing.
    AllowedPattern: "[0-9]+"
  LicenseKeyName:
    Type: String
    Description: Your AWS Secrets Manager secret name which holds the New Relic ingest license key.
    AllowedPattern: "[\\w/_-]+"
  # SecurityGroupIds:
  #   Type: List<AWS::EC2::SecurityGroup::Id>
  #   Description: The list of Security Group IDs for the Lambda function's VPC configuration.
  # SubnetIds:
  #   Type: List<AWS::EC2::Subnet::Id>
  #   Description: The list of Subnet IDs for the Lambda function's VPC configuration.

Globals:
  Function:
    MemorySize: 256
    Timeout: 10
    Environment:
      Variables:
        # agent distributed tracing config
        NEW_RELIC_ACCOUNT_ID: !Ref NRAccountId # New Relic account ID
        NEW_RELIC_TRUSTED_ACCOUNT_KEY: !Ref NRTrustedAccountKey # New Relic account ID or parent ID
        NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true # DT

        # agent serverless config
        NEW_RELIC_NO_CONFIG_FILE: true # Agent uses environment variables in Lambda
        NEW_RELIC_NATIVE_METRICS_ENABLED: false # Reduce cold start duration by not collecting VM metrics
        NEW_RELIC_LOG_ENABLED: true # Agent logs
        NEW_RELIC_LOG: stdout # Agent log path
        NEW_RELIC_LOG_LEVEL: info # Agent log level: fatal, error, warn, info, debug, or trace
        NEW_RELIC_CLOUD_AWS_ACCOUNT_ID: !Ref AWS::AccountId # AWS account ID

        # extension config
        NEW_RELIC_LICENSE_KEY_SECRET: !Ref LicenseKeyName # Secrets Manager secret name for the extension (can override with env var NEW_RELIC_LICENSE_KEY)
        # NEW_RELIC_LICENSE_KEY: !Ref LicenseKey                         # New Relic ingest key, overrides Secrets Manager
        NEW_RELIC_LAMBDA_EXTENSION_ENABLED: true # Enable/disable extension
        NEW_RELIC_DATA_COLLECTION_TIMEOUT: 2s # Reduce timeout duration when "Telemetry client error" happens
        NEW_RELIC_EXTENSION_LOGS_ENABLED: true # Enable/disable NR_EXT log lines
        NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: true # Send function logs
        NEW_RELIC_EXTENSION_SEND_EXTENSION_LOGS: false # Also send extension logs
        NEW_RELIC_EXTENSION_LOG_LEVEL: DEBUG # INFO or DEBUG
        NEW_RELIC_COLLECT_TRACE_ID: true # Collect trace IDs

Resources:
  KmullaneyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Tags:
        - Key: owner
          Value: kmullaney
        - Key: reason
          Value: demo
        - Key: description
          Value: "Secrets Manager access"
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # - Sid: AWSLambdaVPCAccess
              #   Effect: Allow
              #   Action:
              #     - 'ec2:CreateNetworkInterface'
              #     - 'ec2:DescribeNetworkInterfaces'
              #     - 'ec2:DescribeSubnets'
              #     - 'ec2:DeleteNetworkInterface'
              #     - 'ec2:AssignPrivateIpAddresses'
              #     - 'ec2:UnassignPrivateIpAddresses'
              #   Resource: '*'
              - Sid: GetSecretValue
                Effect: Allow
                Action: "secretsmanager:GetSecretValue"
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${LicenseKeyName}-*"
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Sid: CloudWatchMetricsAccess
                Effect: Allow
                Action:
                  - "cloudwatch:PutMetricData"
                Resource: "*"
                Condition:
                  StringEquals:
                    "cloudwatch:namespace":
                      - "AWS/Lambda"

  # -------------------------------------------------

  KmullaneySamEsmNodejs22x:
    Type: AWS::Serverless::Function
    Properties:
      # In this example, we're using the SAM CLI to package and deploy our lambda. SAM will transform this value during the publish step.
      CodeUri: ./src/esm/
      Description: An ESM Lambda function that bypasses the New Relic wrapper for improved cold start performance
      Role: !GetAtt KmullaneyLambdaExecutionRole.Arn
      Handler: /opt/nodejs/node_modules/newrelic-esm-lambda-wrapper/index.handler
      Runtime: nodejs22.x
      PackageType: Zip
      FunctionName: kmullaney-sam-esm-nodejs22x
      Environment:
        Variables:
          # agent serverless config
          NEW_RELIC_APP_NAME: kmullaney-sam-esm-nodejs22x # Should be set but not used in the New Relic UI, entity names come from the AWS integration
          NEW_RELIC_LAMBDA_HANDLER: function.handler # Your function's actual handler if not using manual wrapping method
          # NODE_OPTIONS: --experimental-loader newrelic/esm-loader.mjs.     # Required for ESM functions that use the New Relic loader
          # NEW_RELIC_USE_ESM: true                                        # ESM functions that use async/await and not callbacks
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicNodeJS22X-slim:11
      Tags:
        owner: kmullaney
        reason: "new ESM wrapper"
        description: "nodejs22 ESM handler wrapper for improved cold start performance"

  KmullaneySamEsmNodejs22xLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${KmullaneySamEsmNodejs22x}"
      RetentionInDays: 7

  # -------------------------------------------------

  KmullaneySamExtensionOnlyNodejs22x:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/extension-only/
      Description: An extension-only layer with layerless instrumentation
      # If using the extension-only layer, there is no handler wrapper
      Handler: function.handler
      Runtime: nodejs22.x
      Role: !GetAtt KmullaneyLambdaExecutionRole.Arn
      PackageType: Zip
      FunctionName: kmullaney-sam-extension-only-nodejs22x
      Environment:
        Variables:
          NEW_RELIC_APP_NAME: kmullaney-sam-extension-only-nodejs22x # Should be set but not used in the New Relic UI, entity names come from the AWS integration
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicLambdaExtension:56
      Tags:
        owner: kmullaney
        reason: "test extension-only layer"
        description: "nodejs22 extension-only layer with vendored agent"

  KmullaneySamExtensionOnlyNodejs22xLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${KmullaneySamExtensionOnlyNodejs22x}"
      RetentionInDays: 7

  # -------------------------------------------------

  KmullaneySamAwsRecordMetricNodejs22x:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/record-metric/
      Description: An extension-only layer with layerless instrumentation that records a custom metric
      Handler: newrelic-lambda-wrapper.handler
      Runtime: nodejs22.x
      Role: !GetAtt KmullaneyLambdaExecutionRole.Arn
      PackageType: Zip
      FunctionName: kmullaney-sam-aws-record-metric-nodejs22x
      Environment:
        Variables:
          NEW_RELIC_APP_NAME: kmullaney-sam-aws-record-metric-nodejs22x # Should be set but not used in the New Relic UI, entity names come from the AWS integration
          NEW_RELIC_LAMBDA_HANDLER: function.handler # Your function's actual handler if not using manual wrapping method for better ESM cold start performance
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicNodeJS22X:46
      Tags:
        owner: kmullaney
        reason: "reproduction"
        description: "test aws record metric with node.js agent"

  KmullaneySamAwsRecordMetricNodejs22xLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${KmullaneySamAwsRecordMetricNodejs22x}"
      RetentionInDays: 7

  # -------------------------------------------------

  KmullaneySamDefaultNodejs20xArm64:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/default/
      Description: Testing new Rust extension
      Handler: newrelic-lambda-wrapper.handler
      Runtime: nodejs20.x
      Architectures: [arm64]
      Role: !GetAtt KmullaneyLambdaExecutionRole.Arn
      PackageType: Zip
      FunctionName: kmullaney-sam-default-nodejs20x-arm64
      Environment:
        Variables:
          NEW_RELIC_APP_NAME: kmullaney-sam-default-nodejs20x-arm64
          NEW_RELIC_LAMBDA_HANDLER: index.handler
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicNodeJS20XARM64:99
      Tags:
        owner: kmullaney
        reason: "reproduction"
        description: "test sending of telemetry with new Rust extension"

  KmullaneySamDefaultNodejs20xArm64LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${KmullaneySamDefaultNodejs20xArm64}"
      RetentionInDays: 7
