AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: And example of a simple instrumented NodeJS Lambda

Parameters:
  NewRelicAccountId:
    Type: String
    Description: Your New Relic account ID; necessary for distributed tracing.
    AllowedPattern: "[0-9]+"
  NewRelicTrustedAccountKey:
    Type: String
    Description: Your New Relic parent account ID or account ID if no parent; necessary for distributed tracing.
    AllowedPattern: "[0-9]+"
  LicenseKeyName:
    Type: String
    Description: Your AWS Secrets Manager secret name which holds the New Relic ingest license key.
    AllowedPattern: "[\\w/_-]+"
  NewRelicHost:
    Type: String
    Description: The New Relic collector host for the agent.
    Default: collector.newrelic.com
  NewRelicLogEndpoint:
    Type: String
    Description: The New Relic log endpoint for the extension.
    Default: https://log-api.newrelic.com/log/v1
  NewRelicMetricEndpoint:
    Type: String
    Description: The New Relic metric endpoint for the extension.
    Default: https://metric-api.newrelic.com/metric/v1
  NewRelicTelemetryEndpoint:
    Type: String
    Description: The New Relic telemetry endpoint for the extension, if not using APM mode.
    Default: https://cloud-collector.newrelic.com/aws/lambda/v1
  # SecurityGroupIds:
  #   Type: List<AWS::EC2::SecurityGroup::Id>
  #   Description: The list of Security Group IDs for the Lambda function's VPC configuration.
  # SubnetIds:
  #   Type: List<AWS::EC2::Subnet::Id>
  #   Description: The list of Subnet IDs for the Lambda function's VPC configuration.

Globals:
  Function:
    MemorySize: 256
    Timeout: 10
    Environment:
      Variables:
        # agent distributed tracing config
        NEW_RELIC_ACCOUNT_ID: !Ref NewRelicAccountId # New Relic account ID
        NEW_RELIC_TRUSTED_ACCOUNT_KEY: !Ref NewRelicTrustedAccountKey # New Relic account ID or parent ID
        NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true # DT

        # agent serverless config
        NEW_RELIC_NO_CONFIG_FILE: true # Agent uses environment variables in Lambda
        NEW_RELIC_NATIVE_METRICS_ENABLED: false # Enable native metrics for VM/Environment data harvesting
        NEW_RELIC_LOG_ENABLED: true # Agent logs
        NEW_RELIC_LOG: stdout # Agent log path
        NEW_RELIC_LOG_LEVEL: info # Agent log level: fatal, error, warn, info, debug, or trace
        NEW_RELIC_CLOUD_AWS_ACCOUNT_ID: !Ref AWS::AccountId # AWS account ID

        # extension config
        NEW_RELIC_LICENSE_KEY_SECRET: !Ref LicenseKeyName # Secrets Manager secret name for the extension (can override with env var NEW_RELIC_LICENSE_KEY)
        # NEW_RELIC_LICENSE_KEY: !Ref LicenseKey                         # New Relic ingest key, overrides Secrets Manager
        NEW_RELIC_LAMBDA_EXTENSION_ENABLED: true # Enable/disable extension
        NEW_RELIC_DATA_COLLECTION_TIMEOUT: 3s # Reduce timeout duration when "Telemetry client error" happens
        NEW_RELIC_EXTENSION_LOGS_ENABLED: true # Enable/disable NR_EXT log lines
        NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: true # Send function logs
        NEW_RELIC_EXTENSION_SEND_EXTENSION_LOGS: true # Also send extension logs
        NEW_RELIC_EXTENSION_SEND_PLATFORM_LOGS: true # Also send platform logs
        NEW_RELIC_EXTENSION_LOG_LEVEL: DEBUG # INFO or DEBUG
        NEW_RELIC_COLLECT_TRACE_ID: true # Collect trace IDs

Resources:
  KmullaneyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Tags:
        - Key: owner
          Value: kmullaney
        - Key: reason
          Value: demo
        - Key: description
          Value: "Secrets Manager access"
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # - Sid: AWSLambdaVPCAccess
              #   Effect: Allow
              #   Action:
              #     - 'ec2:CreateNetworkInterface'
              #     - 'ec2:DescribeNetworkInterfaces'
              #     - 'ec2:DescribeSubnets'
              #     - 'ec2:DeleteNetworkInterface'
              #     - 'ec2:AssignPrivateIpAddresses'
              #     - 'ec2:UnassignPrivateIpAddresses'
              #   Resource: '*'
              - Sid: GetSecretValue
                Effect: Allow
                Action: "secretsmanager:GetSecretValue"
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${LicenseKeyName}-*"
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Sid: CloudWatchMetricsAccess
                Effect: Allow
                Action:
                  - "cloudwatch:PutMetricData"
                Resource: "*"
                Condition:
                  StringEquals:
                    "cloudwatch:namespace":
                      - "AWS/Lambda"

  # -------------------------------------------------

  KmullaneySamEsmApmNodejs22x:
    Type: AWS::Serverless::Function
    Properties:
      # In this example, we're using the SAM CLI to package and deploy our lambda. SAM will transform this value during the publish step.
      CodeUri: ./src/esm/
      Description: An ESM Lambda function that uses the new ESM wrapper for improved cold start performance in APM mode
      Role: !GetAtt KmullaneyLambdaExecutionRole.Arn
      Handler: /opt/nodejs/node_modules/newrelic-esm-lambda-wrapper/index.handler
      Runtime: nodejs22.x
      PackageType: Zip
      FunctionName: kmullaney-sam-esm-apm-nodejs22x
      Environment:
        Variables:
          # --- New Relic APM + Serverless Convergence Configuration ---
          # 1. Enable APM mode for the New Relic Lambda layer.
          # NR_TAGS is needed if no cloud integration exists.
          NEW_RELIC_APM_LAMBDA_MODE: "true"
          NR_TAGS: "NR.Apm.Lambda.Mode:true"

          # agent serverless config
          NEW_RELIC_APP_NAME: kmullaney-sam-esm-apm-nodejs22x
          NEW_RELIC_LAMBDA_HANDLER: function.handler

          # extension config
          NEW_RELIC_LICENSE_KEY_SECRET: !Ref LicenseKeyName

          # --- Environment Configuration ---
          # The following endpoints are for sending data to the New Relic various us/eu/staging environments.
          NEW_RELIC_HOST: !Ref NewRelicHost
          NEW_RELIC_LOG_ENDPOINT: !Ref NewRelicLogEndpoint
          NEW_RELIC_METRIC_ENDPOINT: !Ref NewRelicMetricEndpoint
          NEW_RELIC_TELEMETRY_ENDPOINT: !Ref NewRelicTelemetryEndpoint # Only needed if not using APM mode
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicNodeJS22X-slim:28
      Tags:
        # 2. Add the required tag to identify this as a Lambda function in APM mode.
        # If no cloud integration exists, these tags will not get sent to New Relic. Use NR_TAGS instead.
        NR.Apm.Lambda.Mode: "true"
        owner: kmullaney
        reason: "new ESM wrapper"
        description: "nodejs22 ESM handler wrapper for improved cold start performance in APM mode"

  KmullaneySamEsmApmNodejs22xLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${KmullaneySamEsmApmNodejs22x}"
      RetentionInDays: 7

  # -------------------------------------------------

  KmullaneySamExtensionOnlyNodejs22x:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/extension-only/
      Description: An extension-only layer with layerless instrumentation
      # If using the extension-only layer, there is no handler wrapper
      Handler: function.handler
      Runtime: nodejs22.x
      Role: !GetAtt KmullaneyLambdaExecutionRole.Arn
      PackageType: Zip
      FunctionName: kmullaney-sam-extension-only-nodejs22x
      Environment:
        Variables:
          NEW_RELIC_APP_NAME: kmullaney-sam-extension-only-nodejs22x # Should be set but not used in the New Relic UI, entity names come from the AWS integration
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicLambdaExtension:64
      Tags:
        owner: kmullaney
        reason: "test extension-only layer"
        description: "nodejs22 extension-only layer with vendored agent"

  KmullaneySamExtensionOnlyNodejs22xLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${KmullaneySamExtensionOnlyNodejs22x}"
      RetentionInDays: 7

  # -------------------------------------------------

  KmullaneySamAwsRecordMetricNodejs22x:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/record-metric/
      Description: An extension-only layer with layerless instrumentation that records a custom metric
      Handler: newrelic-lambda-wrapper.handler
      Runtime: nodejs22.x
      Role: !GetAtt KmullaneyLambdaExecutionRole.Arn
      PackageType: Zip
      FunctionName: kmullaney-sam-aws-record-metric-nodejs22x
      Environment:
        Variables:
          NEW_RELIC_APP_NAME: kmullaney-sam-aws-record-metric-nodejs22x # Should be set but not used in the New Relic UI, entity names come from the AWS integration
          NEW_RELIC_LAMBDA_HANDLER: function.handler # Your function's actual handler if not using manual wrapping method for better ESM cold start performance
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicNodeJS22X-slim:28
      Tags:
        owner: kmullaney
        reason: "reproduction"
        description: "test aws record metric with node.js agent"

  KmullaneySamAwsRecordMetricNodejs22xLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${KmullaneySamAwsRecordMetricNodejs22x}"
      RetentionInDays: 7

  # -------------------------------------------------

  KmullaneySamDefaultNodejs20xArm64:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/default/
      Description: Testing new Rust extension
      Handler: newrelic-lambda-wrapper.handler
      Runtime: nodejs20.x
      Architectures: [arm64]
      Role: !GetAtt KmullaneyLambdaExecutionRole.Arn
      PackageType: Zip
      FunctionName: kmullaney-sam-default-nodejs20x-arm64
      Environment:
        Variables:
          NEW_RELIC_APP_NAME: kmullaney-sam-default-nodejs20x-arm64
          NEW_RELIC_LAMBDA_HANDLER: index.handler
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicNodeJS20XARM64-slim:28
      Tags:
        owner: kmullaney
        reason: "reproduction"
        description: "test sending of telemetry with new Rust extension"

  KmullaneySamDefaultNodejs20xArm64LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${KmullaneySamDefaultNodejs20xArm64}"
      RetentionInDays: 7

Outputs:
  KmullaneySamEsmApmNodejs22xArn:
    Description: "ARN for the New Relic ESM APM Node.js 22.x Lambda Function"
    Value: !GetAtt KmullaneySamEsmApmNodejs22x.Arn
