AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Python 3.12 Lambda with custom attribute and custom event, telemetry shipped via New Relic extension

Parameters:
  NRAccountId:
    Type: String
    Description: Your New Relic account ID; necessary for distributed tracing.
    AllowedPattern: "[0-9]+"
  NRTrustedAccountKey:
    Type: String
    Description: Your New Relic parent account ID or account ID if no parent; necessary for distributed tracing.
    AllowedPattern: "[0-9]+"
  LicenseKeyName:
    Type: String
    Description: Your AWS Secrets Manager or Parameter Store name which holds the New Relic ingest license key.
    AllowedPattern: "[\\w/_-]+"

Globals:
  Function:
    MemorySize: 256
    Timeout: 20
    Environment:
      Variables:
        # agent distributed tracing config
        NEW_RELIC_ACCOUNT_ID: !Ref NRAccountId
        NEW_RELIC_TRUSTED_ACCOUNT_KEY: !Ref NRTrustedAccountKey
        NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true

        # agent serverless config
        NEW_RELIC_NO_CONFIG_FILE: true
        NEW_RELIC_PACKAGE_REPORTING_ENABLED: false
        NEW_RELIC_LOG_ENABLED: true
        NEW_RELIC_LOG: stderr
        NEW_RELIC_LOG_LEVEL: info
        NEW_RELIC_CLOUD_AWS_ACCOUNT_ID: !Ref AWS::AccountId

        # extension config
        NEW_RELIC_LAMBDA_EXTENSION_ENABLED: true
        NEW_RELIC_DATA_COLLECTION_TIMEOUT: 3s
        NEW_RELIC_EXTENSION_LOGS_ENABLED: true
        NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: true
        NEW_RELIC_EXTENSION_SEND_EXTENSION_LOGS: true
        NEW_RELIC_EXTENSION_SEND_PLATFORM_LOGS: true
        NEW_RELIC_EXTENSION_LOG_LEVEL: DEBUG

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Tags:
        - Key: owner
          Value: kmullaney
        - Key: reason
          Value: testing
        - Key: description
          Value: "python312 instrumentation"
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: GetSecretValue
                Effect: Allow
                Action: "secretsmanager:GetSecretValue"
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${LicenseKeyName}-*"
              - Sid: GetParameterStoreValue
                Effect: Allow
                Action: "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/NEW_RELIC_LICENSE_KEY"
              - Sid: KmsDecrypt
                Effect: Allow
                Action: "kms:Decrypt"
                Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*"
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Sid: CloudWatchMetricsAccess
                Effect: Allow
                Action:
                  - "cloudwatch:PutMetricData"
                Resource: "*"
                Condition:
                  StringEquals:
                    "cloudwatch:namespace":
                      - "AWS/Lambda"
        - PolicyName: LambdaXRayAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "xray:PutTraceSegments"
                  - "xray:PutTelemetryRecords"
                Resource: "*"

  KmullaneySamPython312:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: kmullaney-sam-python-312
      CodeUri: .
      Description: Python 3.12 Lambda with custom attribute and custom event.
      Handler: newrelic_lambda_wrapper.handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Zip
      Tracing: Active
      Environment:
        Variables:
          NEW_RELIC_APP_NAME: kmullaney-sam-python-312
          NEW_RELIC_LAMBDA_HANDLER: function.handler
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicPython:3
      Tags:
        owner: kmullaney
        reason: testing
        description: "python3.12 instrumentation with custom attribute and custom event"

  KmullaneySamPython312LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${KmullaneySamPython312}"
      RetentionInDays: 7

Outputs:
  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt KmullaneySamPython312.Arn
